# 移除了顶部的 'version: '3.8'' 这一行

services:
  player-app:
    # 确保 build 的值是 '.'，代表当前目录
    build: .
    container_name: media-player-container
    ports:
      - "9528:9528" # HTTP Port for Web App and Proxy
      - "9527:9527" # WebSocket Port
    volumes:
      # Mount volumes for persistent data storage
      # This ensures your downloaded media and playlist survive container restarts.
      - ./data/videos:/app/download/Player/videos
      - ./data/music:/app/download/Player/music
      - ./data/albumArt:/app/download/Player/albumArt
    restart: unless-stopped